# Generated by Django 3.2 on 2022-09-23 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dadeline', models.DateField()),
                ('salary_range', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('stream', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('demands', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collegeprofile')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collegeprofile')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobcard')),
            ],
        ),
    ]
