# Generated by Django 3.2 on 2022-09-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
