# Generated by Django 3.2 on 2022-09-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobcard_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='teachers',
        ),
    ]
